export const defaultTheme = {
  colorTextBase: "#333333",
  colorWhite: "#ffffff",
  colorGray: "#f6f6f6",
  colorBgPrimary: "#d8ecfe",
  colorFeaturesFarmBg: "#e1edce",
  colorFarmCategory: "#88aa4d",
  colorFeaturesShopBg: "#f8ddd7",
  colorShopCategory: "#f75531",
  colorButton: "#fc9b27",
  colorButtonHover: "#fc7427",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSize: "18px",
  lineHeight: "27px",
  indent: "20px",
  pagePadding: "90px",
  pageWidth: "1280px",
};
